version: '3.8'

services:
  # Frontend service
  frontend:
    environment:
      - NODE_ENV=uat
    command: yarn dev
    
  # Backend service
  backend:
    environment:
      - NODE_ENV=uat
    command: yarn dev
    
  # Use local services for UAT
  mongodb:
    ports:
      - "27017:27017"
      
  redis:
    ports:
      - "6379:6379"
      
  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"
      
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
