version: '3.8'

services:
  # Backend API
  api:
    build: .
    ports:
      - "3030:3030"
    env_file:
      - .env
    environment:
      # Override REDIS host for containerized environment
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    restart: unless-stopped



  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes



  # Redis Admin Interface (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
