version: '3.8'

services:
  # Backend API
  api:
    build: .
    ports:
      - "3030:3030"
    env_file:
      - .env
    environment:
      # Override Redis + Mongo hosts for containerized environment
      - REDIS_URI=redis://redis:6379
      - MONGODB_URI=mongodb://mongo:27017/jobfinder
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
    command: sh -lc "yarn install --frozen-lockfile && yarn dev"
    restart: unless-stopped

  # MongoDB
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped


  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes



  # Redis Admin Interface (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
