version: '3.8'

services:
  # Backend API - Production
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app-network

  # Redis Cache - Production
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpassword}
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
