import users from './users/users.service.js';
import refreshToken from './refresh-token/refresh-token.service.js';
import upload from './upload/upload.service.js';
import companies from './companies/companies.service.js';
import companyVerifications from './company-verifications/company-verifications.service.js';
import invites from './invites/invites.service.js';
import notifications from './notifications/notifications.service.js';
import shortlists from './shortlists/shortlists.service.js';
import favorites from './favorites/favorites.service.js';
import threads from './threads/threads.service.js';
import messages from './messages/messages.service.js';
import emailVerification from './email-verification/email-verification.service.js';
import jobListings from './job-listings/job-listings.service.js';
import savedJobs from './saved-jobs/saved-jobs.service.js';
import likedJobs from './liked-jobs/liked-jobs.service.js';
import applications from './applications/applications.service.js';
import adminMonitoring from './admin-monitoring/admin-monitoring.service.js';
import studentInternship from './student-internship/student-internship.service.js';
import studentDashboard from './student-dashboard/student-dashboard.service.js';
import companyDashboard from './company-dashboard/company-dashboard.service.js';
import adminDashboard from './admin-dashboard/admin-dashboard.service.js';
import employmentRecords from './employment-records/employment-records.service.js';
import timesheets from './timesheets/timesheets.service.js';
import internshipExtensions from './internship-extensions/internship-extensions.service.js';
import internshipTerminations from './internship-terminations/internship-terminations.service.js';
import resignations from './resignations/resignations.service.js';
import earlyCompletions from './early-completions/early-completions.service.js';
import employmentDetail from './employment-detail/employment-detail.service.js';
import universities from './universities/universities.service.js';
import programmes from './programmes/programmes.service.js';
import programmeCandidates from './programme-candidates/programme-candidates.service.js';
import shares from './shares/shares.service.js';

export default function (app) {
  app.configure(users);
  app.configure(refreshToken);
  app.configure(upload);
  app.configure(companies);
  app.configure(companyVerifications);
  app.configure(invites);
  app.configure(notifications);
  app.configure(shortlists);
  app.configure(favorites);
  // Ensure job listings are available before dependent services
  app.configure(jobListings);
  app.configure(savedJobs);
  app.configure(likedJobs);
  app.configure(applications);
  app.configure(threads);
  app.configure(messages);
  app.configure(emailVerification);
  app.configure(adminMonitoring);
  app.configure(studentInternship);
  app.configure(studentDashboard);
  app.configure(companyDashboard);
  app.configure(adminDashboard);
  app.configure(employmentRecords);
  app.configure(timesheets);
  app.configure(internshipExtensions);
  app.configure(internshipTerminations);
  app.configure(resignations);
  app.configure(earlyCompletions);
  app.configure(employmentDetail);
  app.configure(universities);
  app.configure(programmes);
  app.configure(programmeCandidates);
  app.configure(shares);
};
