name: CI/CD Sebastian Branch

on:
  push:
    branches: [ sebastian ]
  pull_request:
    branches: [ sebastian ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install
      - name: Run linting
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
        env:
          MONGODB_URI: mongodb://localhost:27017/job-finder-test
          REDIS_URI: redis://localhost:6379

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

  deploy-production:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/sebastian'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Production Environment
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 103.209.156.198
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/job-finder-production
            git fetch origin
            git checkout sebastian
            git pull origin sebastian
            yarn install
            cd frontend && yarn install && yarn build && cd ..
            cd backend && yarn install && cd ..
            pm2 restart job-finder-backend-prod
            pm2 restart job-finder-frontend-prod
