name: Deploy to Staging

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test --if-present

      - name: Build application
        run: npm run build --if-present

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/job-finder-staging
            git fetch origin
            git reset --hard origin/staging
            docker-compose -f docker-compose.staging-final.yml down
            docker-compose -f docker-compose.staging-final.yml build --no-cache
            docker-compose -f docker-compose.staging-final.yml up -d
            echo "Staging deployment completed at $(date)"

      - name: Health Check
        run: |
          sleep 30
          curl -f https://staging.saino365.com/api/ || exit 1
          echo "Staging health check passed"
