name: Deploy to Production

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test --if-present

      - name: Build application
        run: npm run build --if-present

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/job-finder
            git fetch origin
            git reset --hard origin/production
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            echo "Production deployment completed at $(date)"

      - name: Health Check
        run: |
          sleep 30
          curl -f https://jobfinder.saino365.com/api/ || exit 1
          echo "Production health check passed"
